### ISSUE TITLE
is the project maintained?

### ISSUE THREAD

**Issue by ioannis12** [finned-tech/sportsbookreview-scraper#1]
hi, 
congrats for your work! I was wondering if it's still maintained, I tried to run it but didn't work. Maybe it's my problem. 
Although, in the SBR site you can find historical odds from last month only.

**Comment by flancast90** [comment]
Hi @ioannis12 
Yep, this report is still maintained, I just pushed the last update a few hours ago actually. What error do you get when you try to run? It's working fine on my system, and on SBR I can see 10 years of static data pages.

**Comment by ioannis12** [comment]
thanks for the reply!

`C:\Users\giann\sportsbookreview-scraper>python cli.py --sport nfl --start 2011 --end 2023 --filename nfl_12Y.json
Traceback (most recent call last):
  File "C:\Users\giann\sportsbookreview-scraper\cli.py", line 3, in <module>
    from scrapers.sportsbookreview import (
  File "C:\Users\giann\sportsbookreview-scraper\scrapers\sportsbookreview.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`


this is the error message on cmd.

when I look into SBR for example in NBA odds, I can open a page only after 14 Oct.

<img width="867" alt="image" src="https://github.com/finned-tech/sportsbookreview-scraper/assets/39949669/722ecfce-7112-4eb0-8ea9-080348621a1d">

**Comment by flancast90** [comment]
You should be able to pip install requests and any other package errors you get. Max end year is also 2022, as SBR hasn't put data out for 2023. Additionally, we scrape from the static tables SBR publishes, not the dynamic odds like you show in your screenshot.

**Comment by ioannis12** [comment]
ok, thanks. That was helpful!

**Comment by flancast90** [comment]
@ioannis12 , is everything working alright for you now? Wanting to know if I can close this Issue yet or if there's some debugging I need to do...

**Comment by ioannis12** [comment]
Yes , it's working fine!
  

  

  

  
  
  
  
  
>
